# A config file for use with `jekyll serve`.
# This is designed for use in parallel with the production config file,
# which is `_config.yml`.
# This file overrides settings in `_config.yml` and should be invoked
# as follows:
#   `bundle exec jekyll serve --config _config.yml,_config_dev.yml`

# Use dev branch for the theme:
remote_theme: "chriscscott/blog-theme-so-simple@dev"
