# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Christopher Scott's Blog"
email: "christopher@christopherscott.ca"
description: >- # this means to ignore newlines until "baseurl:"
  Rarely updated and seldom read.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://chriscscott.github.io" # the base hostname & protocol for your site, e.g. http://example.com
locale: "en-us"
logo: /images/logo.svg

# For themes that provide social tie-ins:
twitter_username: "ChrisCScott"
github_username:  "ChrisCScott"

# Override default post URL style to omit categories and date:
permalink: /:title

# Allow for manually setting the cut-off for the excerpt:
excerpt_separator: <!--more-->

# Set to true if you don't want to see the author sidebar on posts:
hide_author: true

## Footer content:
footer_links:
  # - title: Facebook
  #   url: https://www.facebook.com/ccscott
  #   icon: fab fa-facebook
  # - title: Twitter
  #   url: https://twitter.com/ChrisCScott
  #   icon: fab fa-twitter
  # - title: Mastodon
  #   url: https://mstdn.ca/@ChrisCScott
  #   icon: fab fa-mastodon
  # - title: Reddit
  #   url: https://www.reddit.com/user/ChrisCScott
  #   icon: fab fa-reddit
  # - title: LinkedIn
  #   url: https://www.linkedin.com/in/christophercscott/
  #   icon: fab fa-linkedin
  # - title: GitHub
  #   url: https://github.com/ChrisCScott
  #   icon: fab fa-github
  - title: Feed
    url: feed.xml
    icon: fas fa-rss
copyright: "© Christopher Scott"

## Site-wide default author:
## (See _data/authors.yml for known author tags)
author: christopherscott

# Set theme:
remote_theme: "chriscscott/blog-theme-so-simple"
# theme: minima 

# Alternative theme options:
# Simples (paid): https://jekyllthemes.io/theme/simples-blog-jekyll-theme
# So Simple: https://jekyllthemes.io/theme/so-simple-theme
# Mediator: https://jekyllthemes.io/theme/mediator
# Reverie: https://jekyllthemes.io/theme/reverie
# Jasper: https://jekyllthemes.io/theme/jasper
# Creative (one-page): https://jekyllthemes.io/theme/creative-theme-jekyll
# Scriptor: https://jekyllthemes.io/theme/scriptor
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: false

# Search full text of posts. (This can slow the site down if there
# are many posts - not likely to be an issue for this site)
search_full_content: true

# Extra metadata supported by jekyll-seo-tags:
social:
  name: Christopher Scott
  links:
    - https://www.facebook.com/ccscott
    - https://twitter.com/ChrisCScott
    - https://mstdn.ca/@ChrisCScott
    - https://www.reddit.com/user/ChrisCScott
    - https://www.linkedin.com/in/christophercscott/
    - https://github.com/ChrisCScott
twitter:
  username: christopherscott
  card: summary
facebook:
  publisher: https://www.facebook.com/ccscott

# Custom tags:
# This image is set
default_image: 
